name: Bug report
description: 不具合用のissueテンプレート
labels: bug
title: 🐛 

body:
  - type: textarea
    id: description
    attributes:
      label: 不具合の説明
      description: エンジニア以外でも理解出来るように、不具合の説明を記述してください。
      placeholder: |
        不具合の状況
    validations:
      required: true

  - type: input
    id: screen_name
    attributes:
      label: 画面名
    validations:
      required: true
      
  - type: dropdown
    id: application_environment
    attributes:
      label: 不具合が発生しているアプリケーションの実行環境
      options: 
        - 開発環境
        - 本番環境
        - その他
      multiple: true
    validations:
      required: true
      
  - type: dropdown
    id: os_environment
    attributes:
      label: 不具合が発生しているOS
      options: 
        - Windows
        - Mac
        - その他
      multiple: true
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 再現方法
      description: 不具合の再現方法を記述してください。
      value: |
        1. 〇〇画面の〇をクリック
        2. 〇を選択し、〇を実行する
        3. 画面に〇〇のエラーメッセージが表示される
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots/Logs
